
from dotenv import load_dotenv
import os

load_dotenv()
DATABASE_URL = os.getenv("DATABASE_URL")
SECRET_KEY = os.getenv("SECRETE_KEY_AUTH")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "60"))

CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY') 
CLOUDINARY_SECRET_API_KEY = os.getenv('CLOUDINARY_SECRET_API_KEY') 
CLOUDINARY_NAME = os.getenv('CLOUDINARY_NAME') 